log_paths:
  - logs/sample.log
  # - /var/log/auth.log
  # - /var/log/syslog
  
patterns:
  # SSH failed logins (covers normal + "invalid user")
  - 'Failed password for (?:invalid user )?.*'

  # Generic PAM authentication failures (covers su/sudo/sshd variants)
  - 'pam_.*\(.*:auth\): authentication failure'

  # su failures
  - 'FAILED SU'

  # sudo wrong password bursts
  - 'sudo: .* incorrect password attempts'

  # Catch-all phrase many PAM modules use
  - 'authentication failure'


email:
  rate_limit_seconds: 300

