# config/settings.yaml

log_paths:
  - logs/sample.log
  # - /var/log/auth.log
  # - /var/log/syslog

patterns:
  - name: error log
    regex: "Error"
    level: critical

  # - name: Sudo Attempt
  #   regex: "sudo: .* : TTY=.* ; PWD=.* ; USER=.* ; COMMAND=.*"
  #   level: warning

email:
  rate_limit_seconds: 300
  subject_prefix: "[LOG ALERT]"

alert_levels:
  critical: true
  warning: true
  info: false

system_settings:
  sleep_interval: 5