# config/settings.yaml

log_paths:
  - logs/sample.log
  # - /var/log/auth.log
  # - /var/log/syslog

patterns:
  - Error
  - failed
  - unauthorized
  - denied

email:
  rate_limit_seconds: 300
  subject_prefix: "[LOG ALERT]"

system_settings:
  sleep_interval: 5